name: Go Tests

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.5

      - name: Run Go format test
        run: make fmt-test

      - name: Run Go vet test
        run: make vet-test

      - name: Run Go unit tests
        run: make unit-test

      - name: Run Go race test
        run: make race-test
